title: Miriam Gold
email: miriamasagold@gmail.com
description: >
   Miriam Asa Gold. Environmental economics, R user and developer.
   Predoctoral researcher at the University of Chicago Energy & Environment Lab
twitter_username: MiriamAsaGold
github_username: miriamasagold
markdown: kramdown
theme: jekyll-theme-minimal
logo: imgs/mimi_pfp.jpg
